In [18]:
# Import libraries
import pandas as pd

# Load the data
file_path = 'Online_Cars_Sale_Marketplace.csv'  # Adjust this if your file path is different
df = pd.read_csv(file_path)

# Step 1: Clean the 'Price' column
# Replace 'Not Priced' with NaN and remove $ and commas
df['Price'] = df['Price'].replace({r'\$': '', ',': '', 'Not Priced': None}, regex=True)
df['Price'] = pd.to_numeric(df['Price'], errors='coerce')

# Step 2: Create a 'PopularityScore'
# Popularity Score = ConsumerRating * ConsumerReviews
df['PopularityScore'] = df['ConsumerRating'] * df['ConsumerReviews']

# Step 3: Group by 'Year', 'Make', 'Model'
grouped = df.groupby(['Year', 'Make', 'Model']).agg({
    'PopularityScore': 'sum',
    'ConsumerRating': 'mean',
    'ConsumerReviews': 'sum',
    'Price': 'mean',
    'Mileage': 'mean'
}).reset_index()

# Step 4: Find the most popular car listing
most_popular_car = grouped.sort_values(by='PopularityScore', ascending=False).head(1)

# Display the result
print("Most Popular Car Listing:")
print(most_popular_car)

# Optional: To see Top 5 most popular cars
top5_popular_cars = grouped.sort_values(by='PopularityScore', ascending=False).head(25)
print("Top 5 Most Popular Cars:")
print(top5_popular_cars)

Most Popular Car Listing:
      Year   Make      Model  PopularityScore  ConsumerRating  \
1336  2019  Honda  CR-V EX-L         388800.0             4.8

      ConsumerReviews         Price       Mileage
1336            81000  32072.726667  29645.073333
Top 5 Most Popular Cars:
      Year       Make                   Model  PopularityScore  \
1336  2019      Honda               CR-V EX-L         388800.0
1335  2019      Honda                 CR-V EX         163296.0
1144  2018     Toyota                RAV4 XLE         125664.0
1141  2018     Toyota                 RAV4 LE         121968.0
1390  2019       Jeep  Grand Cherokee Limited         116121.6
1384  2019       Jeep        Cherokee Limited         109737.6
1350  2019      Honda              Pilot EX-L          64224.0
1023  2018       Jeep  Grand Cherokee Limited          58776.0
1467  2019      Mazda      CX-5 Grand Touring          57408.0
969   2018       Ford            F-150 Lariat          54902.4
1142  2018     Toyota            RAV4 Limited          48048.0
1540  2019        RAM            1500 Laramie          44556.0
1252  2019   Cadillac              XT5 Luxury          44537.2
1593  2019     Toyota                 RAV4 LE          42890.4
1309  2019       Ford               F-150 XLT          40800.0
1590  2019     Toyota          Highlander XLE          40075.2
752   2017       Jeep  Grand Cherokee Limited          38476.8
960   2018       Ford               Escape SE          35315.8
1841  2020       Jeep  Grand Cherokee Limited          34560.0
989   2018      Honda             Accord EX-L          34425.6
1259  2019  Chevrolet             Equinox 1LT          33615.0
1981  2020        RAM            1500 Laramie          31838.4
2020  2020     Toyota              Corolla LE          31757.9
722   2017      Honda               CR-V EX-L          30835.2
1240  2019      Buick        Encore Preferred          29939.0

      ConsumerRating  ConsumerReviews         Price       Mileage
1336             4.8            81000  32072.726667  29645.073333
1335             4.8            34020  30276.111111  29953.190476
1144             4.8            26180  27277.441176  41573.617647
1141             4.8            25410  26231.424242  44267.757576
1390             4.8            24192  35562.231481  37206.055556
1384             4.6            23856  28499.682927  35168.380952
1350             4.8            13380  35560.633333  40276.016667
1023             4.8            12245  32586.935484  46237.064516
1467             4.8            11960  30421.750000  27619.673077
969              4.8            11438  43404.928571  53857.428571
1142             4.8            10010  31687.307692  36677.923077
1540             4.7             9480  47417.100000  41487.200000
1252             4.6             9682  36900.990291  33566.155340
1593             4.6             9324  30395.238095  19680.095238
1309             4.8             8500  39865.550000  34781.300000
1590             4.6             8712  38126.500000  29401.125000
752              4.8             8016  28240.916667  62511.791667
960              4.7             7514  21509.615385  44538.615385
1841             4.8             7200  38749.354167  35525.333333
989              4.8             7172  28977.272727  48812.818182
1259             4.5             7470  24730.166667  30915.111111
1981             4.8             6633  48568.969697  34686.333333
2020             4.7             6757  21338.931034  39548.241379
722              4.8             6424  27857.375000  64485.750000
1240             4.7             6370  23333.085714  21455.142857

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9378 entries, 1 to 9378
Data columns (total 33 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Year                   9378 non-null   int64
 1   Make                   9378 non-null   object
 2   Model                  9378 non-null   object
 3   Used/New               9378 non-null   object
 4   Price                  9373 non-null   float64
 5   ConsumerRating         9378 non-null   float64
 6   ConsumerReviews        9378 non-null   int64
 7   SellerType             9378 non-null   object
 8   SellerName             9378 non-null   object
 9   SellerRating           9378 non-null   float64
 10  SellerReviews          9378 non-null   int64
 11  StreetName             9378 non-null   object
 12  State                  9378 non-null   object
 13  Zipcode                9378 non-null   object
 14  DealType               9156 non-null   object
 15  ComfortRating          9378 non-null   float64
 16  InteriorDesignRating   9378 non-null   float64
 17  PerformanceRating      9378 non-null   float64
 18  ValueForMoneyRating    9378 non-null   float64
 19  ExteriorStylingRating  9378 non-null   float64
 20  ReliabilityRating      9378 non-null   float64
 21  ExteriorColor          9378 non-null   object
 22  InteriorColor          9378 non-null   object
 23  Drivetrain             9378 non-null   object
 24  MinMPG                 9378 non-null   int64
 25  MaxMPG                 9378 non-null   int64
 26  FuelType               9378 non-null   object
 27  Transmission           9378 non-null   object
 28  Engine                 9378 non-null   object
 29  VIN                    9378 non-null   object
 30  Stock#                 9378 non-null   object
 31  Mileage                9378 non-null   int64
 32  PopularityScore        9378 non-null   float64
dtypes: float64(10), int64(6), object(17)
memory usage: 2.4+ MB

In [27]:
# Step 1: Select only the important columns
check_df = df[['Year', 'Make', 'Model', 'ConsumerRating', 'ConsumerReviews']].copy()

# Step 2: Group by Year, Make, Model
duplicates = check_df.groupby(['Year', 'Make', 'Model']).nunique()

# Step 3: Find models where either rating or review count varies
problematic_models = duplicates[(duplicates['ConsumerRating'] > 1) | (duplicates['ConsumerReviews'] > 1)].reset_index()

# Step 4: Show the problematic models
print(f"Number of problematic models: {problematic_models.shape[0]}")
print(problematic_models)

# Step 5: (Optional) Show the actual raw listings for these models
# Create a filter to select those problematic models from the original data
# ----> Use only ['Year', 'Make', 'Model'] when merging to avoid bringing in extra columns
problematic_rows = df.merge(problematic_models[['Year', 'Make', 'Model']], on=['Year', 'Make', 'Model'], how='inner')

# Step 6: Display the raw rows
print("\nProblematic listings:")
print(problematic_rows[['Year', 'Make', 'Model', 'ConsumerRating', 'ConsumerReviews']].sort_values(by=['Year', 'Make', 'Model']))

Number of problematic models: 1
   Year       Make        Model  ConsumerRating  ConsumerReviews
0  2015  Chevrolet  Equinox 1LT               1                2

Problematic listings:
   Year       Make        Model  ConsumerRating  ConsumerReviews
0  2015  Chevrolet  Equinox 1LT             4.6              295
1  2015  Chevrolet  Equinox 1LT             4.6              296

In [31]:

# Find the index of the row with lower ConsumerReviews
drop_idx = problematic_rows.sort_values('ConsumerReviews').index[0]

# Drop it from the main dataframe
df = df.drop(index=drop_idx)

In [37]:
# Group again by Year, Make, Model
grouped = df.groupby(['Year', 'Make', 'Model']).agg({
    'PopularityScore': 'sum',
    'ConsumerRating': 'mean',
    'ConsumerReviews': 'sum',
    'Price': 'mean',
    'Mileage': 'mean'
}).reset_index()

# Sort by Popularity Score descending
most_popular_car = grouped.sort_values(by='PopularityScore', ascending=False).head(25)

# Display the most popular car
print("Most Popular Car Listing After Cleaning:")
print(most_popular_car)

Most Popular Car Listing After Cleaning:
      Year       Make                   Model  PopularityScore  \
1336  2019      Honda               CR-V EX-L         388800.0
1335  2019      Honda                 CR-V EX         163296.0
1144  2018     Toyota                RAV4 XLE         125664.0
1141  2018     Toyota                 RAV4 LE         121968.0
1390  2019       Jeep  Grand Cherokee Limited         116121.6
1384  2019       Jeep        Cherokee Limited         109737.6
1350  2019      Honda              Pilot EX-L          64224.0
1023  2018       Jeep  Grand Cherokee Limited          58776.0
1467  2019      Mazda      CX-5 Grand Touring          57408.0
969   2018       Ford            F-150 Lariat          54902.4
1142  2018     Toyota            RAV4 Limited          48048.0
1540  2019        RAM            1500 Laramie          44556.0
1252  2019   Cadillac              XT5 Luxury          44537.2
1593  2019     Toyota                 RAV4 LE          42890.4
1309  2019       Ford               F-150 XLT          40800.0
1590  2019     Toyota          Highlander XLE          40075.2
752   2017       Jeep  Grand Cherokee Limited          38476.8
960   2018       Ford               Escape SE          35315.8
1841  2020       Jeep  Grand Cherokee Limited          34560.0
989   2018      Honda             Accord EX-L          34425.6
1259  2019  Chevrolet             Equinox 1LT          33615.0
1981  2020        RAM            1500 Laramie          31838.4
2020  2020     Toyota              Corolla LE          31757.9
722   2017      Honda               CR-V EX-L          30835.2
1240  2019      Buick        Encore Preferred          29939.0

      ConsumerRating  ConsumerReviews         Price       Mileage
1336             4.8            81000  32072.726667  29645.073333
1335             4.8            34020  30276.111111  29953.190476
1144             4.8            26180  27277.441176  41573.617647
1141             4.8            25410  26231.424242  44267.757576
1390             4.8            24192  35562.231481  37206.055556
1384             4.6            23856  28499.682927  35168.380952
1350             4.8            13380  35560.633333  40276.016667
1023             4.8            12245  32586.935484  46237.064516
1467             4.8            11960  30421.750000  27619.673077
969              4.8            11438  43404.928571  53857.428571
1142             4.8            10010  31687.307692  36677.923077
1540             4.7             9480  47417.100000  41487.200000
1252             4.6             9682  36900.990291  33566.155340
1593             4.6             9324  30395.238095  19680.095238
1309             4.8             8500  39865.550000  34781.300000
1590             4.6             8712  38126.500000  29401.125000
752              4.8             8016  28240.916667  62511.791667
960              4.7             7514  21509.615385  44538.615385
1841             4.8             7200  38749.354167  35525.333333
989              4.8             7172  28977.272727  48812.818182
1259             4.5             7470  24730.166667  30915.111111
1981             4.8             6633  48568.969697  34686.333333
2020             4.7             6757  21338.931034  39548.241379
722              4.8             6424  27857.375000  64485.750000
1240             4.7             6370  23333.085714  21455.142857